apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: storedb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password
  POSTGRES_HOST_AUTH_METHOD: trust
